### ISSUE TITLE
Service 'graylog' failed to build

### ISSUE THREAD

**Issue by amchawawa** [lephisto/pfsense-analytics#31] opened 2020-06-18 20:47 UTC
tost@siem_soc:~/pfsense-analytics/Docker$ sudo docker-compose up -d
[sudo] password for tost:
Building graylog
Step 1/6 : FROM graylog/graylog:3.1
 ---> ca38a27808e3
Step 2/6 : USER root
 ---> Using cache
 ---> 069030ba8761
Step 3/6 : RUN mkdir -pv /etc/graylog/server/
 ---> Using cache
 ---> b85bcd69ff78
Step 4/6 : COPY ./getGeo.sh /etc/graylog/server/
 ---> Using cache
 ---> b023f4e1942e
Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
 ---> Running in 02dd88419fb8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: geolite.maxmind.com
tar (child): /etc/graylog/server/mm.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh' returned a non-zero code: 2

**Comment by thale13** [comment] 2020-06-23 12:56
You have to create a maxmind account and download the file manually.  

I was able to get past this error by downloading the file manually, putting a web server on my system, and serving out the file with it.
Then you have to update the 'Docker/graylog/getGet.sh' to have you localhost url instead of the maxmind url.  
Then redo the docker-compose.

Probably not the best solution, but it worked.

**Comment by amchawawa** [comment] 2020-06-25 06:42
Thanks, I will try that

**Comment by amchawawa** [comment] 2020-06-25 06:43
> You have to create a maxmind account and download the file manually.
> 
> I was able to get past this error by downloading the file manually, putting a web server on my system, and serving out the file with it.
> Then you have to update the 'Docker/graylog/getGet.sh' to have you localhost url instead of the maxmind url.
> Then redo the docker-compose.
> 
> Probably not the best solution, but it worked.

Thanks, I will try that

**Comment by jeanpaulrh** [comment] 2020-06-30 10:25
A better solution is to create a GeoLite account, find your LICENCE KEY under "My Licence Key" menu voice on the left and then use that key for the permalink you can obtain in the download page.
Use the permalink in the Docker/graylog/getGet.sh file (remember to put quotes around the url) and it should work.

**Comment by vinnie5451** [comment] 2020-06-30 19:06
> A better solution is to create a GeoLite account, find your LICENCE KEY under "My Licence Key" menu voice on the left and then use that key for the permalink you can obtain in the download page.
> Use the permalink in the Docker/graylog/getGet.sh file (remember to put quotes around the url) and it should work.

How did you manage that I used the link with my key and got the same error

**Comment by jeanpaulrh** [comment] 2020-06-30 19:20
I had to delete the container and volumes with
docker system purge. After that it worked

Il giorno mar 30 giu 2020 alle 21:06 vinnie5451 <notifications@github.com>
ha scritto:

**Comment by amchawawa** [comment] 2020-07-01 12:20
Thank you all guys it worked

tost@siem_soc:~/pfsense-analytics/Docker$ sudo docker-compose up -d
Building graylog
Step 1/6 : FROM graylog/graylog:3.1
 ---> ca38a27808e3
Step 2/6 : USER root
 ---> Using cache
 ---> 6789be765e54
Step 3/6 : RUN mkdir -pv /etc/graylog/server/
 ---> Using cache
 ---> 8000a5c414b6
Step 4/6 : COPY ./getGeo.sh /etc/graylog/server/
 ---> e73be3679e9d
Step 5/6 : RUN chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh
 ---> Running in 44d9a7a59fc8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.5M  100 28.5M    0     0  3234k      0  0:00:09  0:00:09 --:--:-- 4906k
GeoLite2-City_20200630/README.txt
GeoLite2-City_20200630/COPYRIGHT.txt
GeoLite2-City_20200630/GeoLite2-City.mmdb
GeoLite2-City_20200630/LICENSE.txt
Removing intermediate container 44d9a7a59fc8
 ---> d9e5c0ddb52c
Step 6/6 : USER graylog
 ---> Running in f87e992df144
Removing intermediate container f87e992df144
 ---> 4a49685ee4de
Successfully built 4a49685ee4de
Successfully tagged pfanalytics_graylog:latest
WARNING: Image for service graylog was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Pulling grafana (grafana/grafana:latest)...
latest: Pulling from grafana/grafana
cbdbe7a5bc2a: Pull complete                                                                                             cc193adfe106: Pull complete                                                                                             6dd39f6ef504: Pull complete                                                                                             79d2085b3346: Pull complete                                                                                             996a0e986e15: Pull complete                                                                                             588c402f2646: Pull complete                                                                                             Digest: sha256:0e8b556a7fc9b95c03669509ec50be19c16b82b9e9078f79fa35a71f484bc047
Status: Downloaded newer image for grafana/grafana:latest
Pulling cerebro (lmenezes/cerebro:latest)...
latest: Pulling from lmenezes/cerebro
8559a31e96f4: Pull complete                                                                                             65306eca6b8e: Pull complete                                                                                             ddbf88050b6e: Pull complete                                                                                             0cb03c61bf26: Pull complete                                                                                             872b276b18ca: Pull complete                                                                                             Digest: sha256:229e776839833fcfb21dac39bb2bd89d59fdb8cdb322036cb15e6cba6e4e5199
Status: Downloaded newer image for lmenezes/cerebro:latest
Pulling kibana (docker.elastic.co/kibana/kibana-oss:6.8.5)...
6.8.5: Pulling from kibana/kibana-oss
c808caf183b6: Already exists                                                                                            1465b32e254a: Pull complete                                                                                             eb08ee32061e: Pull complete                                                                                             90c04dfbe09b: Pull complete                                                                                             057c0ffc2cf4: Pull complete                                                                                             e9703943b905: Pull complete                                                                                             bca68440b194: Pull complete                                                                                             d81b0dacccd2: Pull complete                                                                                             Digest: sha256:0c6ae91ba1b412b2148a4ed9d9c56bce725407242b5e4d80e1d65221efe7df5a
Status: Downloaded newer image for docker.elastic.co/kibana/kibana-oss:6.8.5
Creating pfanalytics_elasticsearch_1 ...
Creating pfanalytics_mongodb_1 ...
Creating pfanalytics_influxdb_1 ...
Creating pfanalytics_mongodb_1
Creating pfanalytics_elasticsearch_1
Creating pfanalytics_elasticsearch_1 ... done                                                                           Creating pfanalytics_kibana_1 ...
Creating pfanalytics_cerebro_1 ...
Creating pfanalytics_kibana_1
Creating pfanalytics_influxdb_1 ... done                                                                                Creating pfanalytics_grafana_1 ...
Creating pfanalytics_mongodb_1 ... done                                                                                 Creating pfanalytics_graylog_1 ...
Creating pfanalytics_graylog_1 ... done                                                                                 tost@siem_soc:~/pfsense-analytics/Docker$

**Comment by amchawawa** [comment] 2020-07-01 12:51
> A better solution is to create a GeoLite account, find your LICENCE KEY under "My Licence Key" menu voice on the left and then use that key for the permalink you can obtain in the download page.
> Use the permalink in the Docker/graylog/getGet.sh file (remember to put quotes around the url) and it should work.

Worked thank you

**Comment by cypherstream** [comment] 2020-07-01 19:38
Confirmed this works.  I had to register at maxmind a few months ago to get the updates to work automatically in pfBlockerNG 

https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=[YOURKEY]&suffix=tar.gz

The only issue is I already have influxdb running on port 8086 on the system for other grafana graphs so I error out since the port is 'already in use'.

**Comment by lephisto** [comment] 2021-02-21 22:49
Stuff fixed in the current Version.

**Closed by lephisto** 2021-02-21 22:49 UTC
