### ISSUE TITLE
firewall logs

### ISSUE THREAD

**Issue by l1b3rt** [lephisto/pfsense-analytics#3] opened 2019-11-22 15:00 UTC
Hi, everything is working fine in Grafana.  DPI is showing correct but only i dont see any firewall Logs. Firewall Logs keeps empty.
Is there a way to fix this?
![image](https://user-images.githubusercontent.com/58079041/69436183-2bf91180-0d41-11ea-91e5-499c9b717de6.png)

**Comment by lephisto** [comment] 2019-11-24 00:13
This is not enough information. Did you connect the Stream in Graylog to the Index? Do you see logs in Graylog?

**Comment by l1b3rt** [comment] 2019-11-24 17:24
yes i connected the Stream in Graylog to the index and i see logs in Graylog. If i go to the dashboard in Grafana i can see the DPI, but Firewall Logs stills keeps beeing empty.

![image](https://user-images.githubusercontent.com/58079041/69498321-1291ca00-0ee7-11ea-9dbb-4664032327eb.png)

**Comment by darlcalos** [comment] 2019-11-24 20:20
Hi, 

I can confirm it's not working. 

![image](https://user-images.githubusercontent.com/58149288/69500917-fcdcce80-0eff-11ea-970b-4515fddcff30.png)

![image](https://user-images.githubusercontent.com/58149288/69500927-082ffa00-0f00-11ea-8c91-30f762b02489.png)

![image](https://user-images.githubusercontent.com/58149288/69500933-167e1600-0f00-11ea-8962-aba4b3b9ceab.png)

![image](https://user-images.githubusercontent.com/58149288/69500941-31508a80-0f00-11ea-862d-979008f8efba.png)

As for me, ntopng/DPI Dashboard works all fine.

**Comment by lephisto** [comment] 2019-11-25 10:25
Have you delete the Index to get it recreated with Indextemplate applied? What does graylog show if you tap on system -> inputs -> show recvd messages? Is the Counter doing something already?

**Comment by darlcalos** [comment] 2019-11-25 10:34
> Have you delete the Index to get it recreated with Indextemplate applied? What does graylog show if you tap on system -> inputs -> show recvd messages? Is the Counter doing something already?

Hi lephisto, 

Yes - the index is recreated in Cerebro. Graylog shows a lot of messages, so that connection is working fine. It seems to be something with ES.. I don't have that skills to actually troubleshoot this alongside with Grafana. 

My timezone is not the same as the one you've chosen. I've changed timezone in the graylog.env and in PfSense, if that could be a mismatch..?

**Comment by l1b3rt** [comment] 2019-11-25 11:07
Hi,
Here the index  also recreated in Cerebro. I see allot of messages when i go to inputs => show recvd messages. Counter is working. Tried to change the timezone in system/pipelines to try if this would change something but now i also don't see my logs anymore if i press on the pfsense stream.
I see the messages/seconds counting but if i press the stream its empty.
![image](https://user-images.githubusercontent.com/58079041/69535301-e7a58580-0f7b-11ea-8f5f-98a1f8b08344.png)

![image](https://user-images.githubusercontent.com/58079041/69535371-0d328f00-0f7c-11ea-9bd0-caca22f63239.png)

![image](https://user-images.githubusercontent.com/58079041/69535254-d3618880-0f7b-11ea-9bf3-c710fcf91285.png)

**Comment by lephisto** [comment] 2019-11-25 16:20
I might have found an issue, hold a second

**Comment by lephisto** [comment] 2019-11-25 17:35
Please try the latest master.

The docker-compose.yml was still messed up a little bit, and caused the portname lookup to fail, which caused the pipeline to fail which caused the utc_timestamp to be not written, which on te other hand is used as time field in grafana.

Also make sure that you have changed the processing order in the Graylog setup to be geoIP last, and Pipline Processor next to last.

Missing Data most times is caused by missing utc_timestamp I have to manually generate because pfSense doesn't send a timezone Information, which causes problems when the time of your pfsense is not set to UTC. (JUst to explain why we need to carry a second timestamp).

**Comment by l1b3rt** [comment] 2019-11-26 20:24
Hi Lephisto,
I tried the latest master. Processing order is fine to. More info is getting now into the Firewall Logs in Grafana. Still have some empty date like: GeoIP Block source ip location by ALL, Top Ip Block by all, Rules triggered on all by country and a few more.
![image](https://user-images.githubusercontent.com/58079041/69669622-7f959300-1092-11ea-81bc-7c21b2490a16.png)
I changed in pipelines => the utc_timstamp. Like the picture here:
![image](https://user-images.githubusercontent.com/58079041/69669767-caafa600-1092-11ea-8bec-682e061583ef.png)
Is it now set to my own timezone or do i need a total new timestamp?

**Comment by lephisto** [comment] 2019-11-26 21:47
Have you enabled the GeoIP Database on the bottom as well? It looks like the GeoIP resolving isn't working, and reason for that in most of the cases is that the pluin simply is not running or the custom index template hasn't been applied.

**Comment by dossjj** [comment] 2019-12-19 03:06
I believe I may be having the same issue. Was this ever resolved?

**Comment by dereitz** [comment] 2020-01-25 02:43
I'm having problems as well with populating my Elasticsearch index.  I've worked through the guide and tried everything I can think of to try from this issue.  Can anyone please help?

**Comment by SalehAlolayan** [comment] 2020-02-14 20:29
same here i get the WHOIS error and the stream is empty even though there is messages are coming

**Comment by dereitz** [comment] 2020-02-14 22:40
I gave up on this project for the time being.  If someone is able to make this work, PLEASE post a response here as I (and I'm sure others) would GREATLY appreciate it!

**Comment by SalehAlolayan** [comment] 2020-02-16 19:15
> 
> 
> I gave up on this project for the time being. If someone is able to make this work, PLEASE post a response here as I (and I'm sure others) would GREATLY appreciate it!

i think i might solved the problems i found few, give me few days to make sure i covered all the point, i have forked the repo and ill update the solution in the my fork

**Comment by lephisto** [comment] 2020-02-16 21:26
Did you follow the instructions, applied the custom index template _and_ deleted the index _afterwards_ again?

**Comment by lephisto** [comment] 2020-02-17 18:21
I am about to double test this right now. maybe somethings have changed in the deps, i'll let you know.

**Comment by dereitz** [comment] 2020-02-17 21:48
Part of the problem for me is I wasn't sure how to troubleshoot why things weren't working.  I tried a few modifications per this issue, but nothing worked.  Would appreciate any pointers and appreciate all your efforts!  I'm sure you put in a lot of hard work on getting this going!!!!!!

**Comment by SalehAlolayan** [comment] 2020-02-22 12:23
> 
> 
> I gave up on this project for the time being. If someone is able to make this work, PLEASE post a response here as I (and I'm sure others) would GREATLY appreciate it!

try my fork, i have added a new file to modified the time zones called time.env, for that now all your containers and host will run in the same time zone of your choose, and i fixed the problem with the getGeo.sh file

**Comment by ShagoY** [comment] 2020-04-30 14:47
@dereitz On pfsensefw datasource, change "Time field name" for "timestamp", it's work for me.

Btw timestamp is totally a mess especially when your pfsense is not in UTC.

**Comment by InacomSj** [comment] 2020-05-01 17:57
> 
> 
> > I gave up on this project for the time being. If someone is able to make this work, PLEASE post a response here as I (and I'm sure others) would GREATLY appreciate it!
> 
> try my fork, i have added a new file to modified the time zones called time.env, for that now all your containers and host will run in the same time zone of your choose, and i fixed the problem with the getGeo.sh file

![imagen](https://user-images.githubusercontent.com/63430807/80828612-f6900400-8bbb-11ea-877e-9c6d3f4f63e4.png)
from fresh install, this came up when using your forge

**Comment by InacomSj** [comment] 2020-05-01 17:58
> 
> 
> @dereitz On pfsensefw datasource, change "Time field name" for "timestamp", it's work for me.
> 
> Btw timestamp is totally a mess especially when your pfsense is not in UTC.

sorry for ignorance, where exactly is that change made and what other change have you made?

**Comment by lephisto** [comment] 2021-02-21 20:31
Fixed in latest rls. Obviously Graylog / ES work nicer togehter now when it comes to timesstamps.

**Closed by lephisto** 2021-02-21 20:31 UTC
