### ISSUE TITLE
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by Novilord** [lephisto/pfsense-analytics#45] opened 2020-11-28 10:18 UTC
No connection to https://geolite.maxmind.com/
This causes the error:
curl: (35) error:1408F10B:SSL routines:ssl3_get_record:wrong version number
tar (child): /etc/graylog/server/mm.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
ERROR: Service 'graylog' failed to build: The command '/bin/sh -c chmod +x /etc/graylog/server/getGeo.sh && /etc/graylog/server/getGeo.sh' returned a non-zero code: 2

OS Debian 10
I would be glad for help or ideas on how to get around this problem.

**Comment by Galaxy740** [comment] 2020-12-01 14:23
Same problem i need to slove it quickly!
Pleas somebody to help!

**Comment by holtdw** [comment] 2021-01-07 15:07
Have been looking to use this application of the script and ran into the same issue with the Maxmind GeoIP download routine.  I believe the root cause is Maxmind now requiring an API key for both the paid and subscribed version.  The getGeo.sh should look something like: 'https://download.maxmind.com/app/geoip_download?edition_id=GeoLite2-City&license_key=YOUR_LICENSE_KEY&suffix=tar.gz'

**Comment by lephisto** [comment] 2021-02-21 20:25
This is fixed in the latest release.

**Closed by lephisto** 2021-02-21 20:25 UTC
